version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app
    command: npm start
    ports:
      - 3000:3000
